#!/bin/bash
# chkconfig: - 90 25
# description: memcached daemon
# processname: memcached

. /etc/rc.d/init.d/functions
. /etc/sysconfig/network

MEMCACHED="/usr/local/memcached/bin/memcached"
SERVER_PORT="11211"

[ -f $MEMCACHED ] || exit 1

start() {
	echo -n $"Starting memcached: "
	daemon $MEMCACHED -u daemon -d -m 2048 -l localhost -p $SERVER_PORT -P /var/run/memcached.pid
	echo
}

stop() {
	echo -n $"Shutting down memcached: "
	killproc memcached
	echo
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		sleep 3
		start
		;;
	*)
		echo $"Usage: $0 {start|stop|restart}"
		exit 1
esac
exit 0