#!/bin/bash
# chkconfig: - 85 15
# description: Nginx is a high-performance web and proxy server.
# processname: nginx

nginxd=/data/webserver/nginx/sbin/nginx
nginx_config=/data/webserver/nginx/conf/nginx.conf
nginx_pid=/data/webserver/nginx/logs/nginx.pid
RETVAL=0
prog="nginx"

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0
[ -x $nginxd ] || exit 0

start() {
	if [ -e $nginx_pid ]; then
		echo "nginx already running...."
		exit 1
	fi
	echo -n $"Starting $prog: "
	daemon $nginxd -c ${nginx_config}
	RETVAL=$?
	echo
	[ $RETVAL = 0 ] && touch /var/lock/subsys/nginx
	return $RETVAL
}

stop() {
	echo -n $"Stopping $prog: "
	killproc $nginxd
	RETVAL=$?
	echo
	[ $RETVAL = 0 ] && rm -f /var/lock/subsys/nginx /data/webserver/nginx/logs/nginx.pid
}

reload() {
	echo -n $"Reloading $prog: "
	killproc $nginxd -HUP
	RETVAL=$?
	echo
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload)
		reload
		;;
	restart)
		stop
		start
		;;
	status)
		status $prog
		RETVAL=$?
		;;
	*)
		echo $"Usage: $prog {start|stop|restart|reload|status|help}"
		exit 1
esac

exit $RETVAL